my_file = open("MyFile.txt", "x")
my_file.close()
my_file = open("MyFile.txt", "a")
my_file.write("Theoretically this code should create a file called MyFile.txt and then append this text to it.")
my_file.close()
